# Batch Gradient Descent

In [154]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import time

In [4]:
x , y = load_diabetes(return_X_y = True)

In [8]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [9]:
x.shape

(442, 10)

In [10]:
y.shape

(442,)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [19]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [20]:
x_test

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

In [21]:
y_train

array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
       160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
       109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
       124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
       185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
       127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
       232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
       222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
       174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
        94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
       154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
       208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
        95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
       138., 139.,  98.,  72.,  25.,  72., 264.,  9

In [22]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [23]:
x_train.shape

(353, 10)

In [24]:
x_test.shape

(89, 10)

In [25]:
y_train.shape

(353,)

In [26]:
y_test.shape

(89,)

In [28]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [33]:
print('coefficients =',reg.coef_)
print('intercept = ',reg.intercept_)

coefficients = [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
intercept =  151.88331005254167


In [34]:
y_pred = reg.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [42]:
reg.predict(x_test[[12]])

array([174.33861649])

In [43]:
y_test[12]

np.float64(244.0)

In [44]:
r2_score(y_test,y_pred)

0.4399338661568969

In [158]:
class GDRegressor:

    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self,x_train,y_train):

        #init our coefficients
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
            # updating all the coeff and intercepts
            y_hat = self.intercept_ + np.dot(x_train,self.coef_)
            intercept_der = -2*np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr*intercept_der)

            coef_der = -2*np.dot((y_train-y_hat),x_train)/x_train.shape[0]
            self.coef_ = self.coef_ - (self.lr*coef_der)

        print(self.intercept_,self.coef_)

    def predict(self,x_test):
        return self.intercept_ + np.dot(x_test,self.coef_)

In [175]:
gdr = GDRegressor(epochs=1000, learning_rate=0.4)

In [176]:
start = time.time()
gdr.fit(x_train,y_train)
print('Time Taken = ',time.time()-start)

152.04695545523967 [  23.72258115 -153.73159869  468.33623372  312.6634481   -29.57078448
 -101.98457793 -193.13547041  109.88215911  425.62365976  108.08959706]
Time Taken =  0.062262535095214844


In [177]:
y_pred = gdr.predict(x_test)

In [178]:
r2_score(y_test,y_pred)

0.45392659741468355

In [179]:
y_pred

array([152.49869128, 197.39517138, 130.01316089, 105.07975264,
       262.19502979, 250.42130139, 111.60410992, 115.3825482 ,
        95.2916631 , 187.44625462, 147.84209449, 172.77111622,
       180.43095336, 138.95185925, 285.69807478,  87.34567048,
       199.07021085, 147.37090563, 133.73662007, 131.04811389,
       145.56791825, 175.06865484, 153.80942436, 175.13795381,
       127.35585127, 222.25144675, 199.84905724, 104.60118558,
        55.49272629, 238.71548104, 243.15300056, 113.83690152,
        68.54284795,  98.19399999, 203.90561357, 164.4354013 ,
       162.37134365, 192.98953491, 113.36043675, 238.34432735,
       140.5324609 , 121.64892717, 187.38498484, 186.72116146,
       174.53950567, 143.63655043, 170.24342872, 296.37235608,
       107.66901663, 173.15257935, 251.99793429, 140.31084784,
       150.31166545, 128.35909826, 191.52039582,  97.93534874,
       134.02800699,  77.50827242, 158.35719454, 153.85191403,
       163.40210915, 163.0018055 , 103.53697639, 223.77

In [180]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])